### ISSUE TITLE
Paper Model can't export

### ISSUE THREAD

**Issue by Batleram** [addam/Export-Paper-Model-from-Blender#69]
Whenever I try to export some objects, this error message appears:

Exception ignored in: <function Unfolder.__del__ at 0x7f580507c048>
Traceback (most recent call last):
  File "/home/atelier/.config/blender/2.80/scripts/addons/io_export_paper_model.py", line 192, in __del__
    self.mesh.delete_uvmap()
AttributeError: 'Unfolder' object has no attribute 'mesh'
Traceback (most recent call last):
  File "/home/atelier/.config/blender/2.80/scripts/addons/io_export_paper_model.py", line 1810, in execute
    unfolder = Unfolder(self.object)
  File "/home/atelier/.config/blender/2.80/scripts/addons/io_export_paper_model.py", line 186, in __init__
    self.mesh = Mesh(bm, ob.matrix_world)
  File "/home/atelier/.config/blender/2.80/scripts/addons/io_export_paper_model.py", line 304, in __init__
    edge.calculate_angle()
  File "/home/atelier/.config/blender/2.80/scripts/addons/io_export_paper_model.py", line 706, in calculate_angle
    self.angle = asin(normal_a.cross(normal_b).dot(self.vector.normalized()))
ValueError: math domain error

location: <unknown location>:-1

It seams pretty random which objects do this. I can provide additional information if needed.

I use Blender 2.8 on ubuntu mate 64bit

**Comment by Batleram** [comment]
I tried the new version tlecomte provided but the problem persists. I can send you the object so you can do some further testing if that is what you wish to do.

**Comment by addam** [comment]
Battleram, the fix provided by tlecomte should certainly fix the error that you posted. If problems persist, please post the whole error message again.
