### ISSUE TITLE
Cannot Save User Preset;

### ISSUE THREAD

**Issue by craighayes** [addam/Export-Paper-Model-from-Blender#79]
Great add-on!

Mac OS 10.13.6 - Blender 2.81a

When I try to save a User Preset for colors, paper size, scale, etc., I get an error and no settings are saved. 

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/startup/bl_operators/presets.py", line 167, in execute
    for rna_path in self.preset_values:
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/modules/bpy_types.py", line 712, in __getattribute__
    return super().__getattribute__(attr)
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/addons/io_export_paper_model.py", line 2293, in preset_values
    properties = op.get_rna().bl_rna.properties.items()
AttributeError: 'BPyOpsSubModOp' object has no attribute 'get_rna'

location: <unknown location>:-1

Thank you, 

Craig

**Comment by addam** [comment]
Fixed.
